# Generated by Django 3.1 on 2022-01-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20220106_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='username',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='name',
            field=models.TextField(null=True, verbose_name='Полное имя пользователя'),
        ),
    ]
