# Generated by Django 3.1 on 2022-01-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20220106_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='external_id',
            field=models.PositiveBigIntegerField(verbose_name='ID телеграмм'),
        ),
    ]
