# Generated by Django 3.1 on 2022-01-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20220108_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='external_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='ID телеграмм'),
        ),
    ]
