# Generated by Django 3.1 on 2022-01-08 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20220108_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='is_in_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.PositiveBigIntegerField(unique=True, verbose_name='ID транзакции')),
                ('amount', models.FloatField(default=0.0, verbose_name='Сумма пополнения')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.tguser')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
