# Generated by Django 3.1 on 2022-01-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20220108_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoice_payload',
            field=models.TextField(null=True, verbose_name='Описание платежа'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_payment_charge_id',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='ID транзакции с системе ЮКасса'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='telegram_payment_charge_id',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='ID транзакции с системе Telegram'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Полное имя пользователя'),
        ),
    ]
