# Generated by Django 3.1 on 2022-01-24 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_remove_transaction_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='is_in_payment',
        ),
    ]
