# Generated by Django 3.1 on 2022-02-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_remove_tguser_is_in_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Статус админа'),
        ),
    ]
